# Generated by Django 4.0.6 on 2022-07-28 07:36

from django.db import migrations, models
import wanda.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_parent_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=wanda.apps.accounts.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=wanda.apps.accounts.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='组织ID'),
        ),
    ]
