# Generated by Django 4.0.6 on 2022-07-28 07:37

from django.db import migrations, models
import wanda.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=wanda.apps.accounts.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
