# Generated by Django 4.0.6 on 2022-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='org_code',
            field=models.CharField(default='oct', max_length=25, unique=True, verbose_name='组织代码'),
            preserve_default=False,
        ),
    ]
