# Generated by Django 4.0.6 on 2022-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_org_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expire_dt',
            field=models.DateTimeField(null=True, verbose_name='过期时间'),
        ),
    ]
