# Generated by Django 4.0.6 on 2022-10-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_project_company'),
        ('accounts', '0007_remove_user_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
