# Generated by Django 4.0.6 on 2022-10-18 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wanda.apps.org.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=wanda.apps.org.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='组织ID')),
                ('org_code', models.CharField(max_length=25, unique=True, verbose_name='组织代码')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='公司名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('is_dept', models.BooleanField(default=False, verbose_name='是否部门')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('expire_dt', models.DateTimeField(null=True, verbose_name='过期时间')),
                ('creator', models.CharField(blank=True, max_length=25, null=True, verbose_name='创建人')),
                ('manager', models.CharField(blank=True, max_length=25, null=True, verbose_name='管理者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='org.organization')),
            ],
        ),
    ]
