# Generated by Django 4.0.6 on 2022-07-28 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wanda.apps.survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_company_expire_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='项目标题')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='accounts.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
