# Generated by Django 4.0.6 on 2022-07-28 10:46

from django.db import migrations, models
import django.db.models.deletion
import wanda.apps.survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('release_dt', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('withdraw_dt', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', related_query_name='survey', to='survey.project')),
            ],
        ),
    ]
