# Generated by Django 4.0.6 on 2022-07-28 11:03

from django.db import migrations, models
import wanda.apps.survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('title', models.CharField(max_length=255, verbose_name='政策名称')),
                ('content', models.TextField(verbose_name='正文')),
                ('content_html', models.TextField(verbose_name='正文html')),
                ('survey', models.ManyToManyField(related_name='policies', related_query_name='policy', to='survey.survey')),
            ],
        ),
    ]
