# Generated by Django 4.0.6 on 2022-07-29 02:41

from django.db import migrations, models
import django.db.models.deletion
import wanda.apps.survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_status_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('gid', models.IntegerField(verbose_name='项目编码')),
                ('seq', models.IntegerField(verbose_name='顺序')),
                ('oid', models.IntegerField(verbose_name='选项id')),
                ('type', models.CharField(default='O', max_length=25, verbose_name='类型')),
                ('disp_code', models.CharField(default='', max_length=255, verbose_name='展示代码')),
                ('open_attrs', models.JSONField(default=wanda.apps.survey.models.option_default_open_attrs, verbose_name='其他')),
                ('plaster_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('gid', models.IntegerField(verbose_name='项目编码')),
                ('cid', models.CharField(max_length=25, verbose_name='问卷ID')),
                ('type', models.CharField(max_length=25, verbose_name='类型')),
                ('_index', models.IntegerField(default=-1, verbose_name='页数')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', related_query_name='page', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('cid', models.CharField(max_length=25, verbose_name='问卷ID')),
                ('gid', models.IntegerField(verbose_name='组ID')),
                ('seq', models.IntegerField(verbose_name='顺序')),
                ('title', models.CharField(max_length=255, verbose_name='题目')),
                ('type', models.CharField(max_length=25, verbose_name='类型')),
                ('fixed', models.BooleanField(default=False)),
                ('_index', models.IntegerField(verbose_name='问卷顺序')),
                ('required', models.BooleanField(default=True, verbose_name='必填')),
                ('disp_code', models.CharField(max_length=255)),
                ('stored', models.BooleanField(default=False, verbose_name='题库')),
                ('qtype', models.CharField(max_length=50, verbose_name='题目类型')),
                ('jump_code', models.CharField(max_length=255, verbose_name='跳转代码')),
                ('pGroupGid', models.IntegerField(default=0, verbose_name='组ID')),
                ('codeSelect', models.BooleanField(default=True, verbose_name='代码选择')),
                ('answerStyle', models.CharField(default='', max_length=50, verbose_name='答案格式')),
                ('group_align', models.CharField(default='vertical', max_length=50, verbose_name='分组排列')),
                ('column_value', models.IntegerField(default=1, verbose_name='列数')),
                ('items', models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='survey.option')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='survey.page')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='survey.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
