# Generated by Django 4.0.6 on 2022-07-29 04:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import wanda.apps.survey.models
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_option_single_multiple'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.CharField(default=wanda.apps.survey.models.nanoid_generate, max_length=25, primary_key=True, serialize=False, verbose_name='系统编码')),
                ('cid', models.CharField(max_length=25, verbose_name='问卷ID')),
                ('gid', models.IntegerField(verbose_name='组ID')),
                ('seq', models.IntegerField(verbose_name='顺序')),
                ('title', models.CharField(max_length=255, verbose_name='题目')),
                ('type', models.CharField(max_length=25, verbose_name='类型')),
                ('fixed', models.BooleanField(default=False)),
                ('_index', models.IntegerField(verbose_name='问卷顺序')),
                ('required', models.BooleanField(default=True, verbose_name='必填')),
                ('disp_code', models.CharField(max_length=255)),
                ('stored', models.BooleanField(default=False, verbose_name='题库')),
                ('qtype', models.CharField(max_length=50, verbose_name='题目类型')),
                ('default_q_timecost', models.IntegerField(default=4, verbose_name='默认答题时间')),
                ('words_number_range', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2)),
                ('items', models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='survey.option')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='survey.page')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='survey.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
