# Generated by Django 4.0.6 on 2022-07-29 04:04

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_blank'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='page',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
