# Generated by Django 4.0.6 on 2022-08-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_survey_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank',
            name='qtype',
            field=models.CharField(default='blank', max_length=50, verbose_name='题目类型'),
        ),
    ]
